author: NOQTA
bugs:
  url: https://github.com/nooqta/kodyfire/issues
dependencies:
  '@angular-devkit/schematics': ^12.2.3
  morphmorph: ^0.1.3
  typescript: ~4.5.5
description: Common types used by kodyfire.
devDependencies:
  '@types/node': ^17.0.14
license: ISC
main: index.js
name: kodyfire-core
repository:
  directory: packages/kodyfire-core
  type: git
  url: https://github.com/nooqta/kodyfire.git
scripts:
  build: tsc -p tsconfig.json
  test: 'echo "Error: no test specified" && exit 1'
  watch: tsc -w
version: 0.0.90
